# Generated by Django 3.1.6 on 2021-02-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_moviesearchhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesearchhistory',
            name='genre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moviesearchhistory',
            name='released',
            field=models.DateField(blank=True),
        ),
    ]
